
/*
 * Copyright (c) 2026 HPMicro
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 *
 * Automatically generated by HPM Pinmux Tool
 *
 *
 * Note:
 * PY and PZ IOs: if any SOC pin function needs to be routed to these IOs,
 * besides of IOC, PIOC/BIOC needs to be configured SOC_GPIO_X_xx, so that
 * expected SoC function can be enabled on these IOs.
 */

#ifndef HPM_PINMUX_H
#define HPM_PINMUX_H

#ifdef __cplusplus
extern "C" {
#endif

void init_pins(void);
void init_console_uart_pins(void);
void init_sbus_pins(void);
void init_eeprom_i2c_pins(void);
void init_can_pins(void);
void init_can_term_gpio_pins(void);
void init_rs485_pins(void);
void init_rs232_pins(void);
void init_eth1_rgmii_pins(void);
void init_ecu_output_gpio_pins(void);
void init_ecu_input_gpio_pins(void);
void init_adc_pins(void);
void init_rgb_led_gpio_pins(void);
void init_femc_pins(void);
void init_breathing_led_pwm_pins(void);

#ifdef __cplusplus
}
#endif
#endif /* HPM_PINMUX_H */
