/* Stable diagnostic codes used across state machines and logs. */
#ifndef DIAG_CODES_H
#define DIAG_CODES_H

typedef enum {
    DIAG_OK = 0,
    DIAG_REMOTE_ESTOP_CH13,
    DIAG_REMOTE_ESTOP_SBUS_TIMEOUT,
    DIAG_REMOTE_ESTOP_FAILSAFE,
    DIAG_REMOTE_ESTOP_DECODE_ERRORS,
    DIAG_REMOTE_ESTOP_CREDIBILITY,
    DIAG_REJECT_NOT_PARKED,
    DIAG_REJECT_THROTTLE_NOT_LOW,
    DIAG_REJECT_MODE_PRECONDITION,
    DIAG_REJECT_ACTIVE_TRANSITION,
    DIAG_REJECT_DRIVE_REVERSE_WHILE_MOVING,
    DIAG_REJECT_POWER_PRECONDITION,
    DIAG_REJECT_AUTHORITY_PRECONDITION,
    DIAG_REJECT_ADJUST_OWNER_CONFLICT,
    DIAG_EVENT_EXPIRED,
    DIAG_TRACK_ADJUST_ABORTED,
    DIAG_CPU1_IPC_TIMEOUT,
    DIAG_A_CLASS_FAULT,
    DIAG_CONTROLLED_STOP_ACTIVE,
    DIAG_UNKNOWN
} diag_code_t;

const char *diag_code_name(diag_code_t code);

#endif /* DIAG_CODES_H */
