#include "diag_codes.h"

const char *diag_code_name(diag_code_t code)
{
    switch (code) {
    case DIAG_OK: return "DIAG_OK";
    case DIAG_REMOTE_ESTOP_CH13: return "DIAG_REMOTE_ESTOP_CH13";
    case DIAG_REMOTE_ESTOP_SBUS_TIMEOUT: return "DIAG_REMOTE_ESTOP_SBUS_TIMEOUT";
    case DIAG_REMOTE_ESTOP_FAILSAFE: return "DIAG_REMOTE_ESTOP_FAILSAFE";
    case DIAG_REMOTE_ESTOP_DECODE_ERRORS: return "DIAG_REMOTE_ESTOP_DECODE_ERRORS";
    case DIAG_REMOTE_ESTOP_CREDIBILITY: return "DIAG_REMOTE_ESTOP_CREDIBILITY";
    case DIAG_REJECT_NOT_PARKED: return "DIAG_REJECT_NOT_PARKED";
    case DIAG_REJECT_THROTTLE_NOT_LOW: return "DIAG_REJECT_THROTTLE_NOT_LOW";
    case DIAG_REJECT_MODE_PRECONDITION: return "DIAG_REJECT_MODE_PRECONDITION";
    case DIAG_REJECT_ACTIVE_TRANSITION: return "DIAG_REJECT_ACTIVE_TRANSITION";
    case DIAG_REJECT_DRIVE_REVERSE_WHILE_MOVING: return "DIAG_REJECT_DRIVE_REVERSE_WHILE_MOVING";
    case DIAG_REJECT_POWER_PRECONDITION: return "DIAG_REJECT_POWER_PRECONDITION";
    case DIAG_REJECT_AUTHORITY_PRECONDITION: return "DIAG_REJECT_AUTHORITY_PRECONDITION";
    case DIAG_REJECT_ADJUST_OWNER_CONFLICT: return "DIAG_REJECT_ADJUST_OWNER_CONFLICT";
    case DIAG_EVENT_EXPIRED: return "DIAG_EVENT_EXPIRED";
    case DIAG_TRACK_ADJUST_ABORTED: return "DIAG_TRACK_ADJUST_ABORTED";
    case DIAG_CPU1_IPC_TIMEOUT: return "DIAG_CPU1_IPC_TIMEOUT";
    case DIAG_A_CLASS_FAULT: return "DIAG_A_CLASS_FAULT";
    case DIAG_CONTROLLED_STOP_ACTIVE: return "DIAG_CONTROLLED_STOP_ACTIVE";
    case DIAG_UNKNOWN:
    default:
        return "DIAG_UNKNOWN";
    }
}
